services:
  oracle-db:
    # Imagen oficial de Oracle XE (requiere aceptar licencia)
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=Penguins1223  # Contraseña para SYS/SYSTEM
      - ORACLE_CHARACTERSET=AL32UTF8     # Codificación (opcional)
    ports:
      - "1521:1521"  # Puerto para conexiones JDBC/OCI
      - "5500:5500"  # Oracle Enterprise Manager (OEM)
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persistencia de datos
    restart: unless-stopped

volumes:
  oracle-data: