INSERT INTO LOCATION_TYPE(LOCATION_TYPE_CODE, LOCATION_TYPE_DESCRIPTION)
VALUES ('1', 'PAIS');

INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE, LOCATION_TYPE_DESCRIPTION)
VALUES ('2', 'DEPARTAMENTO');

INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE, LOCATION_TYPE_DESCRIPTION)
VALUES ('3', 'CIUDAD');

INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE, LOCATION_TYPE_DESCRIPTION)
VALUES ('4', 'ÁREA');

INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE, LOCATION_TYPE_DESCRIPTION)
VALUES ('5', 'PROVINCIA');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('57', 'Colombia', '1', NULL);

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('1', 'E.U', '1', NULL);

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('34', 'España', '1', NULL);

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('54', 'Argentina', '1', NULL);

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('05', 'Antioquia', '2', '57');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('81', 'Arauca', '2', '57');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('11', 'Bogotá D.C.', '2', '57');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('15', 'Boyacá', '2', '57');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('25', 'Cundinamarca', '2', '57');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('205', 'Alabama', '4', '1');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('907', 'Alaska', '4', '1');

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME, LOCATION_TYPE_CODE, PARENT_LOCATION)
VALUES ('209', 'California', '4', '1');

COMMIT;
