-- --- Creación de secuencias ---
-- Secuencia para USER_ID
CREATE SEQUENCE SOCIAL_UD.USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para GROUP_ID
CREATE SEQUENCE SOCIAL_UD.GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para MESSAGE_ID
CREATE SEQUENCE SOCIAL_UD.MESSAGE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;